framework:
    messenger:
        transports:
            sync: 'sync://'
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: []
        routing:
            Symfony\Component\Notifier\Message\ChatMessage: sync
            Symfony\Component\Notifier\Message\SmsMessage: sync
